replicaCount: 1
image:
  repository: kutysam/dev-ops-test
  pullPolicy: IfNotPresent
  # Overrides the image tag whose default is the chart appVersion.
  tag: "0.0"
ingress:
  enabled: true
  annotations:
    kubernetes.io/ingress.class: nginx
  hosts:
    - host: 35.184.220.54.nip.io # Change accordingly
      paths:
        - path: /ruby
          pathType: Prefix
  tls: []
resources:
  limits:
    cpu: 300m
    memory: 300Mi
  requests:
    cpu: 300m
    memory: 300Mi
autoscaling:
  enabled: true
  minReplicas: 1
  maxReplicas: 5
  targetCPUUtilizationPercentage: 80
environment:
  - name: DATABASE_URL
    value: postgresql://mypostgresql.default.svc
  - name: DATABASE_PASSWORD
    valueFrom:
      secretKeyRef:
        name: database-secret
        key: rubyapp-password
