version: 2.1
orbs:
  docker: circleci/docker@2.0.1
parameters:
  release-tag:
    description: Tag for Docker and Git used in the Release Workflow.
    type: string
    default: "<< pipeline.number >>.0"
  environment:
    type: string
    default: production

# Filters
feature_filter: &feature_filter
  filters:
    tags:
      only: /^v.*/
    branches:
      ignore: master

release_filter: &release_filter
  filters:
    tags:
      ignore: /.*/
    branches:
      only: master

commands:
  tag_commit:
    parameters:
      release-tag:
        description: Tag for Docker and Git used in the Release Workflow.
        type: string
        default: "<< pipeline.number >>.0"
      environment:
        type: string
        default: production
    steps:
    - run:
        name: Tag current commit with << parameters.release-tag >>
        command: |
          echo "Tagging current commit with << parameters.release-tag >>"
          git config user.email "dev-ops-test-ci@kutysam.com"
          git config user.name "dev-ops-test"
          git tag -a "<< parameters.release-tag >>" -m "<< parameters.release-tag >>"
          git push origin --tags
  install_yq:
    parameters:
      release-tag:
        description: Tag for Docker and Git used in the Release Workflow.
        type: string
        default: "<< pipeline.number >>.0"
      environment:
        type: string
        default: production
    steps:
    - run:
        name: Install yq
        command: |
          wget -q https://github.com/mikefarah/yq/releases/download/v4.5.0/yq_linux_amd64
          mv yq_linux_amd64 /usr/local/bin/yq
          chmod +x /usr/local/bin/yq
  update_repo_image_tag:
    parameters:
      release-tag:
        description: Tag for Docker and Git used in the Release Workflow.
        type: string
        default: "<< pipeline.number >>.0"
      environment:
        type: string
        default: production
    steps:
    - run:
          name: Updating release for argocd.
          command: |
            echo "Auto promoting << parameters.environment >> app to: << parameters.release-tag >>"
            # git config user.email "dev-ops-test-ci@kutysam.com"
            # git config user.name "dev-ops-test"
            yq e ".image.tag = << parameters.release-tag >>" -i ".helm/devopstest/values-<< parameters.environment >>.yaml"
            git add .helm/devopstest/values-<< parameters.environment >>.yaml
            git commit -m "[ci skip] Update image tag to << parameters.release-tag >>"
            git push --set-upstream origin $CIRCLE_BRANCH

jobs:
  tag_commit_update_image_tag:
    docker:
     - image: alpine/git
    parameters:
      release-tag:
        description: Tag for Docker and Git used in the Release Workflow.
        type: string
        default: "<< pipeline.number >>.0"
      environment:
        type: string
        default: production`
    steps:
      - add_ssh_keys
      - checkout
      - tag_commit
      - install_yq
      - update_repo_image_tag

workflows:
  build-docker-image-only:
    jobs:
      - docker/publish:
          image: kutysam/dev-ops-test
          tag: '<< pipeline.number >>.0'
          <<: *release_filter
      - tag_commit_update_image_tag:
          requires:
            - docker/publish
          <<: *release_filter
