apiVersion: kubernetes-client.io/v1
kind: ExternalSecret
metadata:
  name: database-secret # name of the k8s external secret and the k8s secret
spec:
  backendType: gcpSecretsManager
  projectId: rsathishx87
  data:
    - key: rubyapp-password # name of the GCP secret
      name: rubyapp-password # key name in the k8s secret
      version: latest # version of the GCP secret
